# Flyway properties for Maven plugin
# IMPORTANT: Add this file to .gitignore

flyway.url=jdbc:postgresql://localhost:5432/projectsw_db
flyway.user=projectsw_user
flyway.password=sw123
flyway.cleanDisabled=false
