CREATE TABLE tb_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    age INT,
    rank VARCHAR(255),
    mission_id BIGINT,
    CONSTRAINT fk_mission FOREIGN KEY(mission_id) REFERENCES tb_missions(id)
);
