-- Synchronize the sequence for tb_members table
-- This ensures that the next ID generated by the sequence is greater than the max existing ID.
SELECT setval(pg_get_serial_sequence('tb_members', 'id'), COALESCE(max(id), 1), true) FROM tb_members;

-- Synchronize the sequence for tb_missions table
SELECT setval(pg_get_serial_sequence('tb_missions', 'id'), COALESCE(max(id), 1), true) FROM tb_missions;
